version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080